### ISSUE TITLE
Update to 1.0 Bower issues

### ISSUE THREAD

**Issue by jeffrico** [bizley/yii2-content-tools#2]
Hi man,

Great extension!

I was updating the extension today and get following error:

```

  [Composer\Downloader\TransportException]                                     
  The "https://bower.herokuapp.com/packages/search/contenttools" file could n  
  ot be downloaded (HTTP/1.1 404 Not Found)   

```

Any suggestions?
Thanks again

**Comment by bizley** [comment]
Cheers!

This looks like a case already explained and solved [here](https://github.com/francoispluchino/composer-asset-plugin/issues/70#issuecomment-64776637)
I've never seen this issue with my local installation (maybe because of Windows?).
In case this is a matter of composer version make sure you run the current version (with cache cleared and together with fxp/composer-asset-plugin updated to v1.1.2).

Hope this helps. Let me know!

**Comment by bizley** [comment]
If this is not solved with composer and asset-plugin update I'll add the "extra" part to the composer.json file.

**Comment by jeffrico** [comment]
Removing the old fxp plugin, clearing cache, installing the new plugin and updating composer did it for me..

thank you
